# Generated by Django 4.0.5 on 2022-06-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_image_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
